version: '3.2'
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: app
        volumes:
            - ./app:/usr/src/app
        environment:
            - DUMMY=A
        ports:
          - '80:8080'
        restart: always
        tty: true
        command: ./run.sh
