version: '3.2'
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
          args:
              - UID=${LOCALUID}
              - GID=${LOCALUID}        
        container_name: app
        volumes:
            - ./app:/usr/src/app
            - ./downloads:/usr/src/app/downloads:rw
        env_file:
            - ./.env       
        ports:
          - '80:8080'
        restart: always
        tty: true
        command: ./run.sh
